### ISSUE TITLE
Background transparency of search bar

### ISSUE THREAD

**Issue by 0rphee** [RemyIsCool/userChrome.css#1]
Hi! is it normal that the background of the search bar is completely transparent? it seems a little weird to me... (I'm using the firefox [color theme too](https://color.firefox.com/?theme=XQAAAAKGAQAAAAAAAABBKYhm849SCia73laEGccwS-xMDPr5iE6wEt17lnFu4uAqMsdEr66zA4hyQFpjnIdIqexC6jk0ujxh3YezY5q8Yibz3vKnXSdVRwFGs8MGkNcRmXXkVBYSSb5AZytOH-ZH-2fJHXOM2cMauhgxI-owK6hf70XV6B-CNgSQ8ezEFHnV3IYDQizRHgzyz4-QTV3e2qMGHFZQ86mhpKNfHjKK6Ay7Rw6VO4ffFxgcOJhEOGZegOZPzluYPS3grJZyeCZz6Y1js48jUOlOXyXnJ9VOUhG__2C1sgA))

<img width="755" alt="Screenshot 2024-06-29 at 12 35 07 a m" src="https://github.com/RemyIsCool/AnimatedFox/assets/79347623/8a298c2e-44d5-4ee8-99dd-c6afb189fc89">

**Comment by remyrf** [comment]
Maybe the toolbar color was set to be transparent in Firefox Color? Try changing it to something opaque. However, It doesn't look like you installed my Firefox Color theme at all. All the colors are different.

**Comment by 0rphee** [comment]
Well, now that I've looked more into it, the issue was that I enabled Adaptive Bar Color and Firefox Color both at the same time! but Adaptive Bar Color overrode the settings by Firefox Color to transparent... I've found a workaround to use this theme with Adaptive Bar Color here: #3
