### ISSUE TITLE
Top bar looks different from what's shown in the preview

### ISSUE THREAD

**Issue by sinewavess** [RemyIsCool/userChrome.css#4]
I installed the theme on void linux on firefox 127.0.2, and everything works, but the tabs are aligned to the left instead of the center, and the current tab isn't highlighted. Also moving tabs breaks it.

![image](https://github.com/RemyIsCool/AnimatedFox/assets/156376854/d54a3ee2-8b3b-4b42-bbf3-e823d801e135)
Here's an image of 2 tabs

![image](https://github.com/RemyIsCool/AnimatedFox/assets/156376854/b38b3388-7d02-455a-9118-076cb26abe8e)
Here's what happens when i move the second tab to the left and select it
(Putting it in the original location fixes it.)

Can I get help fixing this? Thanks in advance.

**Comment by remyrf** [comment]
For centered tabs, you need to set the option `animatedFox.centeredTabs` to true in about:config. I know about the moving tabs issue, but I don't know how to fix it or if it's even possible. If you want to still use this theme, you can use the keyboard shortcuts ctrl+shift+page up/down to move tabs around.

**Comment by remyrf** [comment]
I just fixed the issue with the background colors, so if you update that issue will be fixed.
