### ISSUE TITLE
Rounded corners frame still showed up on fullscreen (+ Suggesting fix/alternative for minimal close tab button without hiding it)

### ISSUE THREAD

**Issue by KiKaraage** [RemyIsCool/userChrome.css#7]
![gambar](https://github.com/user-attachments/assets/351f3362-2301-4543-8016-87fa23aade81)

And here's my suggestions for close tab button - derived from edge-frfox:
```
#tabbrowser-tabs[closebuttons="activetab"] .tabbrowser-tab:not([pinned], [selected]):hover .tab-close-button {
  display: flex !important;
}
```
![gambar](https://github.com/user-attachments/assets/e0ea089e-86eb-4559-b1cd-9bfafe4053c2)

Great theme btw, a good alternative for Firefox-Alpha. With the Safari look, which I love even more because your approach to hide navbar feels more functional. Thank you so much!

**Comment by remyrf** [comment]
I will consider adding the tab close button as an option. I’m not sure how to fix the rounded corners issue because someone else made it but I’ll see what I can do.

**Comment by KiKaraage** [comment]
This is what I ended up, btw:

```
.tab-close-button:not([selected]), {
  display: none !important;
  -moz-user-focus: none;
}

tab:not([pinned]):not([selected]):not(:hover) .tab-close-button {
  display: none !important;
}

.tab-close-button {
  margin: -6px !important;
  opacity: 0.7;
  border-radius: 10px !important;
}
```

And I also fixed URL suggestion text alignment when centeredUrl is activated (it should only center text in the URL bar, instead of centering the URL suggestions)

```
.urlbarView-url {
	color: var(--toolbar-color) !important;
	text-align: left;
}

@media (-moz-bool-pref: "animatedFox.centeredUrl") {
	#urlbar {
		text-align: center;
		font-size: 1.1em !important;
	}
}
```

What I'm wondering is... how to add margin/gap on `#TabsToolbar > .toolbar-items`? I want some extra spaces, like 5px inline margins (I use centeredTabs), so I can drag the window when needed - but once I had at least 5 tabs, there's no room for that. And when I added margin-inline/margin-left & margin-right, the TabsToolbar is just.. moved, instead of shrinked.

**Comment by KiKaraage** [comment]
![gambar](https://github.com/user-attachments/assets/bd37459b-29b6-490b-9017-9dfa29a893ac)

....Yeah. When the tabs are crowded and there's a pinned tab(s), the TabToolbar is just **moved**, instead of getting shrinked. I can't reach the ">"/scroll forward icon. 

And, when the tabs are crowded + we have pinned tabs, moving mouse/cursor to left side corner will make it hovering the pinned tabs instead. The left part of the website surfing area is basically unusable because of it. 

![gambar](https://github.com/user-attachments/assets/e560e939-2a14-4799-b289-595fbcf22a74)
