### ISSUE TITLE
Not working on Floorp

### ISSUE THREAD

**Issue by aurorarissime** [RemyIsCool/userChrome.css#8]
That's unfortunate because this is my new favorite setup.
Basically any custom modification in about:config doesn't work (except `toolkit.legacyUserProfileCustomizations.stylesheets`) and the pop-up toolbar doesn't seem to exist (I suspect this is because of Floorp's sidebar instead of toolbar?).
If there is a way to make it works on this browser this would be awesome!
![20240719_142904](https://github.com/user-attachments/assets/4c0679cf-9f78-4f15-911c-144258f75771)

**Comment by remyrf** [comment]
I don't know, if there's a way to fix it, but I don't plan on supporting Floorp because I don't use it and it's too different from vanilla Firefox.
